"""The device parameter reference, generated from the config models so it cannot drift: ``python -m ic_opt.em.pcell.reference``.

One table per family: every field with its type, constraints and default, the
fixed port set, the retired names a spec may not use any more. ``docs/em/devices.md``
is this module's output; a test keeps the two equal.
"""

from __future__ import annotations

import sys
from typing import get_args, get_origin

from pydantic import BaseModel
from pydantic.fields import FieldInfo

from ic_opt.em.pcell import GEOMETRY_VERSION
from ic_opt.em.pcell.generator_plugin import PLUGIN_GENERATORS

PORTS = {
    "clean_port_ind_sym": "`P1, N1` (+ `CT` with `ct_metal`)",
    "clean_port_xfm_bs": "`P1, N1, P2, N2` (+ `CTP` / `CTS` with `ct_primary_metal` / `ct_secondary_metal`)",
    "clean_port_xfm_ms": "`P1, N1` = the single-turn primary, `P2, N2` = the multi-turn secondary (+ `CTP` / `CTS`)",
    "clean_port_xfm_balun": "`P1, N1, P2, N2` (+ `CTP` / `CTS`)",
    "clean_port_xfm_tw": "`P1, N1, P2, N2` (no taps)",
    "clean_port_xfm_il": "`P1, N1, P2, N2` (+ `CTP` / `CTS`, upward or downward)",
}


def _type_name(annotation) -> str:
    """``float``, ``float or None``, ``list[str]``, ``dict[str, float] or None`` (no pipes: these land in a Markdown table)."""
    origin = get_origin(annotation)
    if origin is None:
        return getattr(annotation, "__name__", str(annotation))
    args = get_args(annotation)
    if type(None) in args:
        inner = [a for a in args if a is not type(None)]
        return (_type_name(inner[0]) if len(inner) == 1 else " or ".join(_type_name(a) for a in inner)) + " or None"
    return f"{getattr(origin, '__name__', str(origin))}[{', '.join(_type_name(a) for a in args)}]"


def _constraints(field: FieldInfo) -> str:
    parts = []
    for meta in field.metadata:
        for attr, symbol in (("gt", ">"), ("ge", ">="), ("lt", "<"), ("le", "<="), ("multiple_of", "multiple of"), ("min_length", "min length")):
            if hasattr(meta, attr):
                parts.append(f"{symbol} {getattr(meta, attr)}")
    return ", ".join(parts)


def _default(field: FieldInfo) -> str:
    if field.is_required():
        return "required"
    default = field.get_default(call_default_factory=True)
    return "none" if default is None else f"`{default}`"


def family_section(generator_id: str, model: type[BaseModel]) -> str:
    doc = (model.__doc__ or "").strip().split("\n\n")[0].replace("\n", " ")
    lines = [f"## `{generator_id}`", ""]
    if doc:
        lines += [" ".join(doc.split()), ""]
    lines += [f"Ports: {PORTS[generator_id]}", "", "| field | type | constraints | default |", "| --- | --- | --- | --- |"]
    for name, field in model.model_fields.items():
        lines.append(f"| `{name}` | {_type_name(field.annotation)} | {_constraints(field)} | {_default(field)} |")
    retired = getattr(model, "renamed", {})
    if retired:
        lines += ["", "Retired names (refused with the replacement): " + ", ".join(f"`{k}` → `{v}`" if v else f"`{k}` (removed)" for k, v in retired.items())]
    return "\n".join(lines) + "\n"


def render() -> str:
    head = [
        "# Device parameters",
        "",
        f"Generated by `python -m ic_opt.em.pcell.reference` from the config models of `builtin:clean_port` (geometry generation {GEOMETRY_VERSION}). Do not edit by hand.",
        "",
        "Every length is in micrometres and every field name ends in `_um`; counts (`turns`, `secondary_turns`, `ring_count`) have no suffix. "
        "Metals are named as the process profile names its conductors (`\"M6\"`, or whatever a profile calls a metal, such as `\"RDL\"`); "
        "`\"6\"` stands for `\"M6\"`. The bottom metal, the profile's fixture conductor "
        "(`M1` unless `layer_catalog.ground_fixture_conductor` names another), is reserved for the ground fixture. "
        "Common to every family: `process_profile`, `port_order` (exactly the family's fixed port set), `ground_fixture` and `drc_check`.",
        "",
        "## Ground fixture (`ground_fixture`)",
        "",
        "| field | type | constraints | default |",
        "| --- | --- | --- | --- |",
    ]
    from ic_opt.em.pcell.generator_plugin import CleanPortGroundFixtureConfig, CleanPortPgsConfig

    for name, field in CleanPortGroundFixtureConfig.model_fields.items():
        head.append(f"| `{name}` | {_type_name(field.annotation)} | {_constraints(field)} | {_default(field)} |")
    head += ["", "## Patterned ground shield (`pgs`, ind_sym / xfm_bs / xfm_ms)", "", "| field | type | constraints | default |", "| --- | --- | --- | --- |"]
    for name, field in CleanPortPgsConfig.model_fields.items():
        head.append(f"| `{name}` | {_type_name(field.annotation)} | {_constraints(field)} | {_default(field)} |")
    sections = [family_section(gid, gen.config_model) for gid, gen in PLUGIN_GENERATORS.items()]
    return "\n".join(head) + "\n\n" + "\n".join(sections) + "\n" + PLUGIN_SECTION


PLUGIN_SECTION = """\
## A generator of your own (`plugin:`)

A device can name a generator from its own plugin file: `plugin: /abs/path/devices.py`, a module that exports
`PLUGIN_GENERATORS = {generator_id: instance}` of `ic_opt.em.pcell.PassiveDeviceGenerator` subclasses. The pcell
stage validates the device's config with the generator's `config_model` (passing `process_profile` and `port_order`
along with the device's fields), calls `generate`, and runs the same DRC gate as for the families above: the GDS is
audited against the config's `process_profile`, and every conductor the generator's `expected_conductors(config)`
lists must be drawn (the six families declare theirs the same way). A generator that declares none fails every
build unless its config sets `drc_check: false`.
"""


if __name__ == "__main__":
    sys.stdout.write(render())
