"""The device parameter reference, generated from the config models so it cannot drift: ``python -m ic_opt.em.pcell.reference``.

One table per family: every field with its type, constraints and default, the
fixed port set, the retired names a spec may not use any more. ``docs/em/devices.md``
is this module's output; a test keeps the two equal.
"""

from __future__ import annotations

import sys
from typing import get_args, get_origin

from pydantic import BaseModel
from pydantic.fields import FieldInfo

from ic_opt.em.pcell import GEOMETRY_VERSION
from ic_opt.em.pcell.generator_plugin import PLUGIN_GENERATORS

PORTS = {
    "clean_port_ind_sym": "`P1, N1` (+ `CT` with `ct_metal`)",
    "clean_port_xfm_bs": "`P1, N1, P2, N2` (+ `CTP` / `CTS` with `ct_primary_metal` / `ct_secondary_metal`)",
    "clean_port_xfm_ms": "`P1, N1` = the single-turn primary, `P2, N2` = the multi-turn secondary (+ `CTP` / `CTS`)",
    "clean_port_xfm_balun": "`P1, N1, P2, N2` (+ `CTP` / `CTS`)",
    "clean_port_xfm_tw": "`P1, N1, P2, N2` (no taps)",
    "clean_port_xfm_il": "`P1, N1, P2, N2` (+ `CTP` / `CTS`, upward or downward)",
}


def _type_name(annotation) -> str:
    """``float``, ``float or None``, ``list[str]``, ``dict[str, float] or None`` (no pipes: these land in a Markdown table)."""
    origin = get_origin(annotation)
    if origin is None:
        return getattr(annotation, "__name__", str(annotation))
    args = get_args(annotation)
    if type(None) in args:
        inner = [a for a in args if a is not type(None)]
        return (_type_name(inner[0]) if len(inner) == 1 else " or ".join(_type_name(a) for a in inner)) + " or None"
    return f"{getattr(origin, '__name__', str(origin))}[{', '.join(_type_name(a) for a in args)}]"


def _constraints(field: FieldInfo) -> str:
    parts = []
    for meta in field.metadata:
        for attr, symbol in (("gt", ">"), ("ge", ">="), ("lt", "<"), ("le", "<="), ("multiple_of", "multiple of"), ("min_length", "min length")):
            if hasattr(meta, attr):
                parts.append(f"{symbol} {getattr(meta, attr)}")
    return ", ".join(parts)


def _default(field: FieldInfo) -> str:
    if field.is_required():
        return "required"
    default = field.get_default(call_default_factory=True)
    return "none" if default is None else f"`{default}`"


def family_section(generator_id: str, model: type[BaseModel]) -> str:
    doc = (model.__doc__ or "").strip().split("\n\n")[0].replace("\n", " ")
    lines = [f"## `{generator_id}`", ""]
    if doc:
        lines += [" ".join(doc.split()), ""]
    lines += [f"Ports: {PORTS[generator_id]}", "", "| field | type | constraints | default |", "| --- | --- | --- | --- |"]
    for name, field in model.model_fields.items():
        lines.append(f"| `{name}` | {_type_name(field.annotation)} | {_constraints(field)} | {_default(field)} |")
    retired = getattr(model, "renamed", {})
    if retired:
        lines += ["", "Retired names (refused with the replacement): " + ", ".join(f"`{k}` → `{v}`" if v else f"`{k}` (removed)" for k, v in retired.items())]
    if generator_id in NOTES:
        lines += ["", NOTES[generator_id]]
    return "\n".join(lines) + "\n"


def render() -> str:
    head = [
        "# Device parameters",
        "",
        f"Generated by `python -m ic_opt.em.pcell.reference` from the config models of `builtin:clean_port` (geometry generation {GEOMETRY_VERSION}). Do not edit by hand.",
        "",
        "Every length is in micrometres and every field name ends in `_um`; counts (`turns`, `secondary_turns`, `ring_count`) have no suffix. "
        "Metals are named as the process profile names its conductors (`\"M6\"`, or whatever a profile calls a metal, such as `\"RDL\"`); "
        "`\"6\"` stands for `\"M6\"`. The bottom metal, the profile's fixture conductor "
        "(`M1` unless `layer_catalog.ground_fixture_conductor` names another), carries the ground fixture unless `ground_fixture.metal` moves it (below). "
        "Common to every family: `process_profile`, `port_order` (exactly the family's fixed port set), `ground_fixture` and `drc_check`.",
        "",
        "## Ground fixture (`ground_fixture`)",
        "",
        "| field | type | constraints | default |",
        "| --- | --- | --- | --- |",
    ]
    from ic_opt.em.pcell.generator_plugin import CleanPortGroundFixtureConfig, CleanPortPgsConfig

    for name, field in CleanPortGroundFixtureConfig.model_fields.items():
        head.append(f"| `{name}` | {_type_name(field.annotation)} | {_constraints(field)} | {_default(field)} |")
    head += ["", FIXTURE_METAL_NOTE, "", "## Patterned ground shield (`pgs`, ind_sym / xfm_bs / xfm_ms)", "", "| field | type | constraints | default |", "| --- | --- | --- | --- |"]
    for name, field in CleanPortPgsConfig.model_fields.items():
        head.append(f"| `{name}` | {_type_name(field.annotation)} | {_constraints(field)} | {_default(field)} |")
    sections = [family_section(gid, gen.config_model) for gid, gen in PLUGIN_GENERATORS.items()]
    return "\n".join(head) + "\n\n" + "\n".join(sections) + "\n" + TOPOLOGY_SECTION + "\n" + PLUGIN_SECTION


FIXTURE_METAL_NOTE = (
    "`metal` is the conductor the ring, the stubs and their `G<nn>` pins go on. Absent or null: the fixture conductor, the bottom "
    "metal -- the geometry every existing configuration and library row has. `auto`: the highest metal of the profile's stack on "
    "which the device draws nothing (no winding, bridge, crossunder, tap stack, lead or port); refused in reference mode, which has "
    "no stack. A metal name or position: that metal, refused when the device draws anything on it -- EMX refuses a port whose "
    "reference stub lies on the port lead's own metal (`ports ... are not allowed to be on the same edge`), and a footprint measured "
    "by layer needs the fixture's layer to itself. That is the default `metal_rule` (below). Why it matters: a thin bottom metal's "
    "resistance enters every measurement through "
    "the stubs and the ring; on one 1P10M stack a 50 µm transformer measured Qp 14.6 with the fixture on M1, M3 or M6 and 20.2 on "
    "M9, the same as with no fixture at all, while keeping the local reference. A library table is comparable row for row only "
    "with tables built with the same fixture metal; `pgs` keeps the bottom metal (its strips tie to that ring).\n\n"
    "`metal_rule` says what that metal may carry of the device, and needs `metal` (with `metal` absent or null it is refused: "
    "the rule says how a metal is chosen, and the default fixture chooses none). Absent or `free`: nothing, the rule above. "
    "`shared`: the device's internal shapes -- crossunders, bridges -- but no port lead, which is all EMX's constraint asks; "
    "`auto` then takes the highest metal of the stack that carries no port lead and has a pin layer for the G pins, and a "
    "named metal is refused only when it carries a port lead. Each build, under either rule, records the box of the device it "
    "drew around, taken before the fixture (`geometry.device_bbox_um` in `geometry_manifest.json`), and the footprint is read from "
    "that record -- under `shared` the fixture's layer no longer tells the two apart; a row without the record is measured by "
    "layer as before. The DRC gate still exempts `max_width` on the fixture's metal, by layer: "
    "under `shared` that covers the device's internal shapes on it as well, and nothing else of theirs. The families' internal "
    "shapes are as wide as a winding, far below any metal's `max_width`, so nothing is hidden in practice; a plugin family with "
    "wide internal shapes should not use `shared`.\n\n"
    "On a metal chosen under `free` (`metal` set, `auto` or a name) every shape is the ring or a stub, so the gate exempts the "
    "spacing rules there too (`min_space`, `wide_parallel_spacing`): a spacing finding on that metal lies between two shapes "
    "of the fixture -- such as a tap port's stub between the other winding's two stubs (xfm_bs, below). Under `shared`, and "
    "with `metal` absent (the bottom metal, where a patterned ground shield is a real, fabricated structure tied to the "
    "ring), spacing counts as before. Stubs that would touch or overlap are refused when the fixture is laid out, naming the "
    "two ports and the gap: one edge would hold two `G` pins, which EMX refuses."
)

XFM_BS_TAP_NOTE = (
    "Center taps (`ct_primary_metal` / `ct_secondary_metal`). A tap leaves its winding at the closed column, on the centre "
    "line, toward the other winding -- the primary's tap crosses the secondary's opening side and the secondary's the "
    "primary's -- and its lead runs on to the other winding's outer extent (never shorter than its own winding's lead), so "
    "the tap port (`CTP` / `CTS`) sits at the lead's far tip, between the other winding's two ports. A tap metal equal to "
    "its winding's metal (by stack position: `\"6\"`, `\"M6\"` and the position agree) is a same-metal tap: no via stack, "
    "the lead drawn on the winding's own metal as one polygon with the winding, the port on that metal and its pin layer; "
    "where the lead crosses the other winding it is on a different metal, a crossing, not a short. It draws nothing on any "
    "other metal, so `ground_fixture.metal: auto` picks the same metal as for the untapped device. A tap metal below the "
    "winding is a via-stack tap: a W × W via stack at the closed column drops to the tap metal, and the lead, as wide as "
    "the winding, runs there (`auto` then goes below the tap metal). A tap metal above its winding is refused. "
    "`ct_primary_width_um` / `ct_secondary_width_um` set the width of a same-metal tap's lead (absent: the winding's width; "
    "the tap port's automatic stub width follows the lead); they are refused with a via-stack tap and without the matching "
    "tap metal. The tap port's ground stub runs between the other winding's two stubs on the fixture's metal: when that "
    "winding's leads are close together (a small opening), the three stubs can come closer than the fixture metal's "
    "minimum spacing. On a fixture metal chosen under `metal_rule: free` that is the fixture's own spacing and the DRC gate "
    "passes it (`ground_fixture`, above); under `shared`, or on the default bottom metal, it fails the build, and "
    "`primary_port_spacing_um` / `secondary_port_spacing_um` widen the other winding's port pair to make room (nothing "
    "chooses that spacing automatically). Stubs that would touch are refused under any rule."
)

XFM_MS_TAP_NOTE = (
    "Center taps (`ct_primary_metal` / `ct_secondary_metal`). The single-turn primary is tapped as xfm_bs taps a winding "
    "(above): at its closed column, on the centre line, toward the secondary, the lead running on to the secondary's outer "
    "extent (never shorter than the primary's own lead), the port `CTP` at the lead's far tip. A tap metal equal to the "
    "primary's metal (by stack position) is a same-metal tap: no via stack, the lead drawn on the primary's own metal as one "
    "polygon with the winding, the port on that metal and its pin layer. The primary sits above everything the secondary "
    "draws, so the lead crosses the secondary on another metal, a crossing, not a short, and `ground_fixture.metal: auto` "
    "picks the same metal as for the untapped device. A tap metal below the primary is a via-stack tap, its lead as wide as "
    "the primary (`auto` then goes below the tap metal); above the primary it is refused. `ct_primary_width_um` sets the "
    "width of a same-metal tap's lead (absent: the primary's width; the tap port's automatic stub width follows the lead); "
    "it is refused with a via-stack tap and without `ct_primary_metal`. The multi-turn secondary is tapped as `ind_sym` taps "
    "an inductor: a via stack from the midpoint turn down to `ct_secondary_metal`, which sits at least two levels below the "
    "secondary (the secondary's crossunder holds the level in between and crosses the tap's lead path), the lead as wide as "
    "the secondary, the port `CTS` at its tip; there is no same-metal tap on the secondary (a lead on its own metal would "
    "cross its turns) and no width field. The secondary's tap leaves on the side opposite the primary's for an odd "
    "`secondary_turns` and on the primary tap's side, on the same centre line, for an even one: there the two tap ports' "
    "ground stubs overlap and the fixture refuses the build, so a device with both taps has an odd `secondary_turns`."
)

#: A paragraph after a family's field table.
NOTES = {"clean_port_xfm_bs": XFM_BS_TAP_NOTE, "clean_port_xfm_ms": XFM_MS_TAP_NOTE}

TOPOLOGY_SECTION = """\
## Measurement topology (`topology`)

A device's `topology` (a spec field next to its `ports`) states how its S-parameters are measured: `drives`, one
`[plus, minus]` port pair per differential drive (the primary, then the secondary), and `grounded`, the ports held at
0 V. A drive pushes its current in at plus and out at minus. A device without a topology gets one from its ports other
than the `CT*` taps, which are grounded: two ports are one drive, `[P1, N1]`; four ports are two drives with the
secondary reversed, `[[P1, N1], [N2, P2]]` for `P1, N1, P2, N2`, because that is how the families above wind it, so
their `k` is positive.

Only the sign of `k` (`k_lf`, and `k` at a frequency) depends on the drives' polarity. A generator of your own whose
secondary winds the other way measures `k < 0` under that default: the measure stage keeps the point but says so in its
issues, and `lib.load` counts such library rows (`negative_k_lf`). State the drives of such a device, every port
exactly once:

```yaml
topology: {drives: [[P1, N1], [P2, N2]]}          # with taps: grounded: [CTP, CTS]
```
"""

PLUGIN_SECTION = """\
## A generator of your own (`plugin:`)

A device can name a generator from its own plugin file: `plugin: /abs/path/devices.py`, a module that exports
`PLUGIN_GENERATORS = {generator_id: instance}` of `ic_opt.em.pcell.PassiveDeviceGenerator` subclasses. The pcell
stage validates the device's config with the generator's `config_model` (passing `process_profile` and `port_order`
along with the device's fields), calls `generate`, and runs the same DRC gate as for the families above: the GDS is
audited against the config's `process_profile`, and every conductor the generator's `expected_conductors(config)`
lists must be drawn (the six families declare theirs the same way). A generator that declares none fails every
build unless its config sets `drc_check: false`. Its S-parameters are measured with the device's `topology`: the
default above unless the spec states one.
"""


if __name__ == "__main__":
    sys.stdout.write(render())
