"""OCEAN replay script generation and scalar-output parsing (Spectre/OCEAN kernel)."""

from __future__ import annotations

import csv
import math
import re
from dataclasses import dataclass, field
from pathlib import Path

from pydantic import BaseModel, Field, field_validator

from ic_opt.spec import Metric

RESULT_SELECTOR_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
WAVEFORM_RESULT_RE = re.compile(r'\?result\s+"([^"]+)"')
UNSAFE_RE = re.compile(r"outfile\(|system\(|\{\{")
SAFE_IDENTIFIER_RE = re.compile(r"[^A-Za-z0-9_]")
SCALARS_HEADER = ["metric", "value", "unit", "status", "message"]


class WaveformExport(BaseModel):
    name: str = Field(pattern=r"^[A-Za-z_][A-Za-z0-9_]*$")
    expression: str = Field(min_length=1)
    testbench: str | None = None

    @field_validator("expression")
    @classmethod
    def _safe(cls, value: str) -> str:
        if UNSAFE_RE.search(value):
            raise ValueError("waveform expression must not contain outfile(, system( or {{")
        return value


@dataclass
class ScalarRow:
    value: float | None
    unit: str
    status: str            # "pass" | "fail"
    message: str = ""


@dataclass
class Scalars:
    rows: dict[str, ScalarRow] = field(default_factory=dict)
    waveforms: dict[str, Path | None] = field(default_factory=dict)   # export name -> local csv path (None: returned nil)
    attempts: int = 1


def replay_script(metrics: list[Metric], waveforms: list[WaveformExport], *, psf_dir: str, scalars_file: str,
                  waveform_dir: str) -> str:
    """SKILL that reads ``psf_dir`` and writes one TSV row per metric plus waveform CSVs.

    All paths are relative to the OCEAN working directory.
    """
    lines = [
        "; Generated by ic-opt: metric expressions copied verbatim from spec.yaml",
        f"openResults({_skill(psf_dir)})",
        f"out = outfile({_skill(scalars_file)})",
        'fprintf(out "' + "\\t".join(SCALARS_HEADER) + '\\n")',
    ]
    for metric in metrics:
        if metric.result is not None:
            _check_selector(metric.result, f"metric {metric.name} result")
            lines.append(f"selectResult('{metric.result})")
        lines += [
            f"; metric: {metric.name}",
            f"icoptResult = errset({metric.expression} t)",
            "if(icoptResult then",
            "  icoptValue = car(icoptResult)",
            "  if(numberp(icoptValue) then",
            f'    fprintf(out "%s\\t%.16g\\t%s\\tpass\\t\\n" {_skill(metric.name)} icoptValue {_skill(metric.unit)})',
            "  else",
            f'    fprintf(out "%s\\t\\t%s\\tfail\\tnon_scalar\\n" {_skill(metric.name)} {_skill(metric.unit)})',
            "  )",
            "else",
            f'  fprintf(out "%s\\t\\t%s\\tfail\\texpression_error\\n" {_skill(metric.name)} {_skill(metric.unit)})',
            ")",
        ]
    for wf in waveforms:
        var = SAFE_IDENTIFIER_RE.sub("_", wf.name)
        lines.append(f"; waveform export: {wf.name}")
        selector = WAVEFORM_RESULT_RE.search(wf.expression)
        if selector:
            _check_selector(selector.group(1), f"waveform {wf.name} result")
            lines.append(f"selectResult('{selector.group(1)})")
        csv_path = f"{waveform_dir}/{wf.name}.csv"
        lines += [
            f"icoptWave_{var} = {wf.expression}",
            f"if(icoptWave_{var} then",
            f'  icoptWaveOut_{var} = outfile({_skill(csv_path)} "w")',
            f"  ocnPrint(?output icoptWaveOut_{var} ?separator \",\" ?numberNotation 'scientific icoptWave_{var})",
            f"  close(icoptWaveOut_{var})",
            "else",
            f"  ; waveform export {wf.name} returned nil",
            ")",
        ]
    lines += ["close(out)", "exit()"]
    return "\n".join(lines) + "\n"


def parse_scalars(path: Path) -> dict[str, ScalarRow]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if reader.fieldnames != SCALARS_HEADER:
            raise ValueError(f"unexpected scalar header {reader.fieldnames}")
        rows: dict[str, ScalarRow] = {}
        for row in reader:
            name = row["metric"]
            value: float | None = None
            if row["status"] == "pass":
                try:
                    value = float(row["value"])
                except ValueError as exc:
                    raise ValueError(f"metric {name} value is not numeric: {row['value']!r}") from exc
                if not math.isfinite(value):
                    value = None
                    row["status"], row["message"] = "fail", "non_finite"
            rows[name] = ScalarRow(value, row["unit"], row["status"], row["message"])
    return rows


def _skill(value: str) -> str:
    if any(ord(c) < 32 or ord(c) == 127 for c in value):
        raise ValueError(f"control character in SKILL string {value!r}")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _check_selector(value: str, label: str) -> None:
    if not RESULT_SELECTOR_RE.match(value):
        raise ValueError(f"{label} is not a safe OCEAN result selector: {value!r}")
