"""OCEAN replay script generation and scalar-output parsing (Spectre/OCEAN kernel), the waveform files the script
writes and their reader (N-100, ``docs/waveform_export.md``), and the saturation margin read from the operating-point
table the script writes (T17.11)."""

from __future__ import annotations

import csv
import json
import math
import re
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

from pydantic import BaseModel, Field, field_validator

from ic_opt.spec import Metric

RESULT_SELECTOR_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
WAVEFORM_RESULT_RE = re.compile(r'\?result\s+"([^"]+)"')
UNSAFE_RE = re.compile(r"outfile\(|system\(|\{\{")
SAFE_IDENTIFIER_RE = re.compile(r"[^A-Za-z0-9_]")
SCALARS_HEADER = ["metric", "value", "unit", "status", "message"]
OPPOINTS_HEADER = "instance\tquantity\tvalue"
# D8: the quantities kept per transistor, fixed. `gm` first: an instance without it is not a transistor and is left out.
OP_QUANTITIES = ("gm", "region", "ids", "vgs", "vds", "vbs", "vth", "vdsat", "gds", "gmoverid", "cgs", "cgd")
# N-100: the waveform files. Every value is written with this format: sixteen significant digits.
WAVEFORM_PRECISION = "%.16g"
TIMING_FILE = "ocean_timing.tsv"          # beside the scalars: part \t seconds \t outcome, one row per timed part


class WaveformExport(BaseModel):
    name: str = Field(pattern=r"^[A-Za-z_][A-Za-z0-9_]*$")
    expression: str = Field(min_length=1)
    testbench: str | None = None

    @field_validator("expression")
    @classmethod
    def _safe(cls, value: str) -> str:
        if UNSAFE_RE.search(value):
            raise ValueError("waveform expression must not contain outfile(, system( or {{")
        return value


@dataclass
class ScalarRow:
    value: float | None
    unit: str
    status: str            # "pass" | "fail"
    message: str = ""


@dataclass
class Scalars:
    rows: dict[str, ScalarRow] = field(default_factory=dict)
    # export name -> local ``<name>.meta.json`` (None: nothing written -- the expression returned nil, or ``outcomes``
    # says why)
    waveforms: dict[str, Path | None] = field(default_factory=dict)
    attempts: int = 1
    oppoints: Path | None = None           # local oppoints.tsv (None: not asked for)
    outcomes: dict[str, str] = field(default_factory=dict)   # timed part ("waveform:<name>") -> its outcome


def replay_script(metrics: list[Metric], waveforms: list[WaveformExport], *, psf_dir: str, scalars_file: str,
                  waveform_dir: str, oppoint_result: str | None = None, oppoints_file: str | None = None,
                  timing_file: str | None = None) -> str:
    """SKILL that reads ``psf_dir`` and writes one TSV row per metric plus the waveform files and, with ``oppoint_result``
    (the netlist's ``info what=oppoint where=rawfile`` statement), the operating points to ``oppoints_file``.

    Only metrics with an expression are written: a saturation margin (T17.11) is computed by the extract stage from the
    operating points (:func:`saturation_margin`), not by OCEAN.

    Waveforms (N-100, ``docs/waveform_export.md``): each is written from its vectors (``drGetWaveformXVec`` /
    ``drGetWaveformYVec``, ``%.16g``) as a real CSV, ``<name>.csv`` with ``<name>.meta.json``, a family one file per
    member (``<name>__<i>.csv``) with ``<name>.families.json``; not through ``ocnPrint``, whose output is a whitespace
    table of six significant digits and which slows past 10 000 points (PRINT-1048). Each export
    is timed (``measureTime``, wall clock): a line in the OCEAN log and a row of ``timing_file`` (default:
    ``ocean_timing.tsv`` beside ``scalars_file``). A script without waveforms is what it was before.

    All paths are relative to the OCEAN working directory.
    """
    timing = timing_file or _sibling(scalars_file, TIMING_FILE)
    lines = [
        "; Generated by ic-opt: metric expressions copied verbatim from spec.yaml",
        f"openResults({_skill(psf_dir)})",
        f"out = outfile({_skill(scalars_file)})",
        'fprintf(out "' + "\\t".join(SCALARS_HEADER) + '\\n")',
    ]
    for metric in (m for m in metrics if m.expression is not None):
        if metric.result is not None:
            _check_selector(metric.result, f"metric {metric.name} result")
            lines.append(f"selectResult('{metric.result})")
        lines += [
            f"; metric: {metric.name}",
            f"icoptResult = errset({metric.expression} t)",
            "if(icoptResult then",
            "  icoptValue = car(icoptResult)",
            "  if(numberp(icoptValue) then",
            f'    fprintf(out "%s\\t%.16g\\t%s\\tpass\\t\\n" {_skill(metric.name)} icoptValue {_skill(metric.unit)})',
            "  else",
            "    if(null(icoptValue) then",             # SKILL's type(nil) is `list`: say what it is
            f'      fprintf(out "%s\\t\\t%s\\tfail\\tno_value:nil\\n" {_skill(metric.name)} {_skill(metric.unit)})',
            "    else",
            f'      fprintf(out "%s\\t\\t%s\\tfail\\tnon_scalar:%L\\n" {_skill(metric.name)} {_skill(metric.unit)} type(icoptValue))',
            "    )",
            "  )",
            "else",
            f'  fprintf(out "%s\\t\\t%s\\tfail\\texpression_error\\n" {_skill(metric.name)} {_skill(metric.unit)})',
            ")",
        ]
    if waveforms:
        lines += waveform_script(waveforms, waveform_dir=waveform_dir, timing_file=timing)
    lines.append("close(out)")
    if oppoint_result is not None:
        lines += oppoint_script(oppoint_result, oppoints_file)
    lines.append("exit()")
    return "\n".join(lines) + "\n"


# The waveform writer, defined once per script (N-100). SKILL source as it is sent: "\\" is one backslash.
# icoptWriteWave returns list(columns units points), or a string saying why nothing was written; icoptExportWave
# writes a waveform or a family and its JSON files, the meta file last, and returns list(outcome points).
_WAVEFORM_PROCEDURES = r"""; waveform export (ic-opt, N-100): a CSV per waveform written from its vectors, %.16g
procedure(icoptJsonString(s)
  let((out c)
    out = ""
    for(i 1 strlen(s)
      c = substring(s i 1)
      out = strcat(out cond((equal(c "\\") "\\\\") (equal(c "\"") "\\\"") (equal(c "\t") "\\t") (equal(c "\n") "\\n") (equal(c "\r") "\\r") (t c)))
    )
    strcat("\"" out "\"")
  )
)
procedure(icoptJsonValue(v)
  cond(
    (null(v) "null")
    (stringp(v) icoptJsonString(v))
    (symbolp(v) icoptJsonString(get_pname(v)))
    (integerp(v) sprintf(nil "%d" v))
    (floatp(v) sprintf(nil "%.16g" v))
    (t icoptJsonString(sprintf(nil "%L" v)))
  )
)
procedure(icoptJsonList(l)
  strcat("[" buildString(mapcar('icoptJsonValue l) ", ") "]")
)
procedure(icoptVecText(vec what)
  let((v)
    v = car(errset(if(eq(what 'units) vec~>units vec~>name)))
    if(stringp(v) v "")
  )
)
procedure(icoptColumnText(s)
  let((out c)
    out = ""
    for(i 1 strlen(s)
      c = substring(s i 1)
      out = strcat(out if(index("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_" c) c "_"))
    )
    out
  )
)
procedure(icoptXColumn(vec)
  let((name units)
    name = icoptColumnText(icoptVecText(vec 'name))
    units = icoptColumnText(icoptVecText(vec 'units))
    cond((equal(name "") "x") (equal(units "") name) (t strcat(name "_" units)))
  )
)
procedure(icoptWriteWave(w path)
  let((xv yv xt yt n port cols units)
    xv = drGetWaveformXVec(w)
    yv = drGetWaveformYVec(w)
    xt = drGetWaveformXType(w)
    yt = drGetWaveformYType(w)
    n = drVectorLength(xv)
    cond(
      (!memq(xt '(double intlong)) sprintf(nil "unsupported_x:%L" xt))
      (!memq(yt '(double intlong doublecomplex)) sprintf(nil "unsupported_y:%L" yt))
      (drVectorLength(yv) != n sprintf(nil "length_mismatch:%d:%d" n drVectorLength(yv)))
      (t
        if(eq(yt 'doublecomplex) then
          cols = list(icoptXColumn(xv) "re" "im")
          units = list(icoptVecText(xv 'units) icoptVecText(yv 'units) icoptVecText(yv 'units))
        else
          cols = list(icoptXColumn(xv) "y")
          units = list(icoptVecText(xv 'units) icoptVecText(yv 'units))
        )
        port = outfile(path "w")
        fprintf(port "%s\n" buildString(cols ","))
        cond(
          (eq(yt 'doublecomplex)
            for(i 0 n-1
              let((z)
                z = drGetElem(yv i)
                fprintf(port "%.16g,%.16g,%.16g\n" float(drGetElem(xv i)) float(real(z)) float(imag(z)))
              )
            )
          )
          (eq(xt 'double) && eq(yt 'double)
            for(i 0 n-1 fprintf(port "%.16g,%.16g\n" drGetElem(xv i) drGetElem(yv i)))
          )
          (t
            for(i 0 n-1 fprintf(port "%.16g,%.16g\n" float(drGetElem(xv i)) float(drGetElem(yv i))))
          )
        )
        close(port)
        list(cols units n)
      )
    )
  )
)
procedure(icoptFamilyMembers(f prefix)
  let((members m)
    foreach(v famGetSweepValues(f)
      m = famValue(f v)
      if(drIsParamWave(m) then
        members = append(members icoptFamilyMembers(m append(prefix list(v))))
      else
        members = append(members list(list(append(prefix list(v)) m)))
      )
    )
    members
  )
)
procedure(icoptWriteText(path text)
  let((port)
    port = outfile(path "w")
    fprintf(port "%s" text)
    close(port)
  )
)
procedure(icoptExportWave(name value dir expression result)
  let((head written members sweeps indexRows entries file failed points)
    head = strcat("{\"name\": " icoptJsonString(name) ", \"expression\": " expression ", \"result\": " result)
    cond(
      (null(value) list("nil" 0))
      (drIsParamWave(value)
        members = icoptFamilyMembers(value nil)
        if(!members then
          list("empty_family" 0)
        else
          for(d 0 length(car(car(members))) - 1
            sweeps = append(sweeps list(car(errset(famGetSweepName(value d)))))
          )
          points = 0
          for(i 0 length(members) - 1
            unless(failed
              file = sprintf(nil "%s__%d.csv" name i)
              written = icoptWriteWave(cadr(nth(i members)) strcat(dir "/" file))
              if(stringp(written) then
                failed = sprintf(nil "member_%d:%s" i written)
              else
                points = points + caddr(written)
                indexRows = append(indexRows list(strcat("{\"index\": " sprintf(nil "%d" i) ", \"file\": " icoptJsonString(file)
                                                 ", \"values\": " icoptJsonList(car(nth(i members))) "}")))
                entries = append(entries list(strcat("{\"file\": " icoptJsonString(file) ", \"columns\": "
                                                     icoptJsonList(car(written)) ", \"units\": " icoptJsonList(cadr(written))
                                                     sprintf(nil ", \"points\": %d}" caddr(written)))))
              )
            )
          )
          if(failed then
            list(failed 0)
          else
            icoptWriteText(strcat(dir "/" name ".families.json")
                           strcat("{\"name\": " icoptJsonString(name) ", \"sweeps\": " icoptJsonList(sweeps)
                                  ", \"members\": [" buildString(indexRows ", ") "]}\n"))
            icoptWriteText(strcat(dir "/" name ".meta.json")
                           strcat(head ", \"kind\": \"family\", \"index\": " icoptJsonString(strcat(name ".families.json"))
                                  ", \"members\": [" buildString(entries ", ") "]"
                                  ", \"separator\": \",\", \"precision\": \"%.16g\"}\n"))
            list("written" points)
          )
        )
      )
      (!drIsWaveform(value) list(sprintf(nil "not_a_waveform:%L" type(value)) 0))
      (t
        file = strcat(name ".csv")
        written = icoptWriteWave(value strcat(dir "/" file))
        if(stringp(written) then
          list(written 0)
        else
          icoptWriteText(strcat(dir "/" name ".meta.json")
                         strcat(head ", \"kind\": \"waveform\", \"file\": " icoptJsonString(file)
                                ", \"columns\": " icoptJsonList(car(written)) ", \"units\": " icoptJsonList(cadr(written))
                                sprintf(nil ", \"points\": %d" caddr(written))
                                ", \"separator\": \",\", \"precision\": \"%.16g\"}\n"))
          list("written" caddr(written))
        )
      )
    )
  )
)"""


def waveform_script(waveforms: list[WaveformExport], *, waveform_dir: str, timing_file: str) -> list[str]:
    """The replay script's waveform part (N-100): the writer once, then per export its expression (inside ``errset``,
    as a metric's), its result selected first when the expression names one, and the export -- both timed. ``timing_file``
    is opened here (``"w"``) and gets one row per export; the OCEAN log one line."""
    names = {w.name for w in waveforms}
    for wf in waveforms:                       # a family's members are <name>__<i>.csv: no export may be one of them
        clash = re.match(r"^(.+)__\d+$", wf.name)
        if clash and clash.group(1) in names:
            raise ValueError(f"waveform {wf.name} has the name of a member file of waveform {clash.group(1)}")
    lines = [*_WAVEFORM_PROCEDURES.splitlines(), f'icoptTiming = outfile({_skill(timing_file)} "w")']
    for wf in waveforms:
        lines.append(f"; waveform export: {wf.name}")
        selector = WAVEFORM_RESULT_RE.search(wf.expression)
        result = "null"
        if selector:
            _check_selector(selector.group(1), f"waveform {wf.name} result")
            lines.append(f"selectResult('{selector.group(1)})")
            result = json.dumps(selector.group(1))
        lines += [
            "icoptWave = nil",
            f"icoptWaveEval = measureTime(icoptWave = car(errset({wf.expression} t)))",
            'icoptWaveDone = list("error" 0)',
            (f"icoptWaveWrite = measureTime(icoptWaveDone = car(errset(icoptExportWave({_skill(wf.name)} icoptWave "
             f"{_skill(waveform_dir)} {_skill(json.dumps(wf.expression))} {_skill(result)}) t)) || list(\"error\" 0))"),
            (f'printf("ic-opt waveform export %s: %s, %d point(s), %.3f s (expression %.3f s, file %.3f s)\\n" '
             f"{_skill(wf.name)} car(icoptWaveDone) cadr(icoptWaveDone) caddr(icoptWaveEval) + caddr(icoptWaveWrite) "
             "caddr(icoptWaveEval) caddr(icoptWaveWrite))"),
            (f'fprintf(icoptTiming "waveform:%s\\t%.6f\\t%s\\n" {_skill(wf.name)} caddr(icoptWaveEval) + caddr(icoptWaveWrite) '
             "car(icoptWaveDone))"),
        ]
    lines.append("close(icoptTiming)")
    return lines


def oppoint_script(result: str, oppoints_file: str) -> list[str]:
    """The replay script's operating-point part. It runs after the metrics and waveforms, with their file closed, so it
    cannot change one. Every call that can fail is inside ``errset``; rows are collected first and written only when the
    whole read went through, so a failure leaves the file empty (as does a result without operating points).

    OCEAN names a result after the statement only when the statement has one of the design environment's own names
    (``dcOpInfo``, a symbol); any other statement's result is the string ``<name>-info`` (``"icoptOpInfo-info"``), and
    selecting the bare name fails with "Results ... are not available" (real run, 2026-09-28). So the result is looked up
    in ``results()`` under both forms. A quantity is read with ``pv`` from that result -- the call that returned numbers
    in that run for both forms --, then with ``OP``, which reads the design environment's own result only, under the name
    as ``outputs()`` gives it and with a leading ``/``.
    Instance names are written as ``outputs()`` gives them, with ``\\``, tab and newline escaped
    (:func:`parse_oppoints` undoes it)."""
    _check_selector(result, "operating-point result")
    quantities = " ".join(_skill(q) for q in OP_QUANTITIES[1:])
    return [
        "; operating points (ic-opt): after the metrics, whose file is closed; nothing here can change one",
        "procedure(icoptOpEscape(s)",
        "  let((escaped c)",
        '    escaped = ""',
        "    for(i 1 strlen(s)",
        "      c = substring(s i 1)",
        r'      escaped = strcat(escaped cond((equal(c "\\") "\\\\") (equal(c "\t") "\\t") (equal(c "\n") "\\n") (t c)))',
        "    )",
        "    escaped",
        "  )",
        ")",
        "icoptOpResult = nil",
        "foreach(icoptOpCandidate car(errset(results()))",
        "  let((name)",
        '    name = sprintf(nil "%s" icoptOpCandidate)',
        f"    when(!icoptOpResult && (equal(name {_skill(result)}) || equal(name {_skill(result + '-info')}))",
        "      icoptOpResult = icoptOpCandidate",
        "    )",
        "  )",
        ")",
        "procedure(icoptOpValue(inst q)",
        "  let((v)",
        "    v = car(errset(pv(inst q ?result icoptOpResult)))",
        "    unless(numberp(v) v = car(errset(OP(inst q))))",
        '    unless(numberp(v) || equal(substring(inst 1 1) "/") v = car(errset(OP(strcat("/" inst) q))))',
        "    if(numberp(v) v nil)",
        "  )",
        ")",
        "icoptOpRows = nil",
        "icoptOpRead = errset(",
        "  when(icoptOpResult && errset(selectResult(icoptOpResult))",
        "    foreach(icoptOpInst car(errset(outputs()))",
        "      errset(",
        "        let((name gm row v)",
        "          name = if(symbolp(icoptOpInst) get_pname(icoptOpInst) icoptOpInst)",
        f"          gm = icoptOpValue(name {_skill(OP_QUANTITIES[0])})",
        "          when(gm",
        rf'            row = list(sprintf(nil "%s\t{OP_QUANTITIES[0]}\t%.16g\n" icoptOpEscape(name) float(gm)))',
        f"            foreach(q list({quantities})",
        "              v = icoptOpValue(name q)",
        r'              when(v row = cons(sprintf(nil "%s\t%s\t%.16g\n" icoptOpEscape(name) q float(v)) row))',
        "            )",
        "            icoptOpRows = append(icoptOpRows reverse(row))",
        "          )",
        "        )",
        "      )",
        "    )",
        "  )",
        ")",
        f'icoptOpOut = car(errset(outfile({_skill(oppoints_file)} "w")))',
        "when(icoptOpOut",
        "  when(icoptOpRead && icoptOpRows",
        r'    fprintf(icoptOpOut "instance\tquantity\tvalue\n")',          # OPPOINTS_HEADER
        '    foreach(icoptOpRow icoptOpRows fprintf(icoptOpOut "%s" icoptOpRow))',
        "  )",
        "  close(icoptOpOut)",
        ")",
    ]


def parse_oppoints(path: Path) -> dict[str, dict[str, float]] | None:
    """``oppoints.tsv`` -> {instance: {quantity: value}}; None when the file is missing or holds no row (no operating
    points in the results). Instances without ``gm`` and non-finite values are left out, as the script leaves out what
    has no number. A malformed row is an error (ValueError): the extract stage then keeps no operating points."""
    if not path.exists():
        return None
    text = path.read_bytes().decode("utf-8")           # not read_text: a carriage return inside a name stays in it
    rows = [line for line in text.split("\n") if line]
    if not rows:
        return None
    if rows[0] != OPPOINTS_HEADER:
        raise ValueError(f"unexpected operating-point header {rows[0]!r}")
    table: dict[str, dict[str, float]] = {}
    for line in rows[1:]:
        fields = line.split("\t")
        if len(fields) != 3 or fields[1] not in OP_QUANTITIES:
            raise ValueError(f"malformed operating-point row {line!r}")
        value = float(fields[2])
        if math.isfinite(value):
            table.setdefault(_unescape(fields[0]), {})[fields[1]] = value
    table = {name: q for name, q in table.items() if "gm" in q}
    return table or None


def _unescape(name: str) -> str:
    return re.sub(r"\\(.)", lambda m: {"t": "\t", "n": "\n"}.get(m.group(1), m.group(1)), name)


def saturation_margin(table: dict[str, dict[str, float]] | None, instances: Sequence[str]) -> tuple[float | None, list[str]]:
    """The worst saturation margin of ``instances`` in an operating-point table (T17.11): the smallest ``|vds| - |vdsat|``,
    in volts, positive while a transistor is beyond its saturation voltage -- absolute values, because a PMOS's table
    carries negative voltages. ``(value, [])``, or ``(None, missing)`` naming every instance without a row, or whose row
    lacks ``vds`` or ``vdsat``; with no table (``None``: the results held no operating points) that is every instance.

    An instance is found under its own name, else with a leading ``/`` added or taken off: the table names instances as the
    simulator reports them (``/M1``, ``/I0/M3``), and ``M1`` names the same transistor."""
    rows = table or {}
    margins, missing = [], []
    for name in instances:
        row = rows.get(name)
        if row is None:
            row = rows.get(name[1:] if name.startswith("/") else f"/{name}")
        if row is None or "vds" not in row or "vdsat" not in row:
            missing.append(name)
        else:
            margins.append(abs(row["vds"]) - abs(row["vdsat"]))
    return (None, missing) if missing else (min(margins), [])


def parse_scalars(path: Path) -> dict[str, ScalarRow]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if reader.fieldnames != SCALARS_HEADER:
            raise ValueError(f"unexpected scalar header {reader.fieldnames}")
        rows: dict[str, ScalarRow] = {}
        for row in reader:
            name = row["metric"]
            value: float | None = None
            if row["status"] == "pass":
                try:
                    value = float(row["value"])
                except ValueError as exc:
                    raise ValueError(f"metric {name} value is not numeric: {row['value']!r}") from exc
                if not math.isfinite(value):
                    value = None
                    row["status"], row["message"] = "fail", "non_finite"
            rows[name] = ScalarRow(value, row["unit"], row["status"], row["message"])
    return rows


@dataclass
class TimingRow:
    part: str              # "waveform:<name>"
    seconds: float         # wall clock, measured inside OCEAN (measureTime)
    outcome: str           # "written", "nil", "not_a_waveform:<type>", ...


def parse_timing(path: Path) -> list[TimingRow]:
    """``ocean_timing.tsv`` -> its rows; [] when the file is missing. A row that does not parse is left out: the timing
    is a record of the run, never a reason to fail one."""
    if not path.exists():
        return []
    rows = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        fields = line.split("\t")
        try:
            rows.append(TimingRow(fields[0], float(fields[1]), fields[2]))
        except (IndexError, ValueError):
            continue
    return rows


@dataclass
class WaveformTable:
    """One CSV: its columns (``x,y`` or ``x,re,im``, the first named after the x quantity and unit), their units, and the
    rows as floats. A family member also carries its sweep values, outermost sweep first."""
    file: Path
    columns: list[str]
    units: list[str]
    rows: list[tuple[float, ...]]
    values: list = field(default_factory=list)


@dataclass
class ExportedWaveform:
    name: str
    kind: str                       # "waveform" | "family"
    expression: str
    result: str | None
    tables: list[WaveformTable]     # one for a waveform; one per member for a family, in the index's order
    sweeps: list[str] = field(default_factory=list)      # a family's sweep names, outermost first


def read_waveform(meta_path: Path) -> ExportedWaveform:
    """A waveform export as the replay script wrote it (N-100, ``docs/waveform_export.md``), read from its
    ``<name>.meta.json``: every CSV it names is read with ``csv.reader`` and must have the header the meta file gives, as
    many fields per row, numbers only, and the point count the meta file gives; a family's index must name the same
    files. Anything else is a ValueError naming the file."""
    meta = _json(meta_path)
    folder = meta_path.parent
    try:
        kind, name = meta["kind"], meta["name"]
        if kind == "waveform":
            tables = [_read_csv(folder / meta["file"], meta["columns"], meta["units"], meta["points"])]
            sweeps: list[str] = []
        elif kind == "family":
            index = _json(folder / meta["index"])
            members = index["members"]
            if [m["file"] for m in members] != [m["file"] for m in meta["members"]]:
                raise ValueError(f"{meta['index']} and {meta_path.name} name different files")
            tables = [_read_csv(folder / m["file"], m["columns"], m["units"], m["points"], values=list(i["values"]))
                      for m, i in zip(meta["members"], members)]
            sweeps = list(index["sweeps"])
        else:
            raise ValueError(f"{meta_path.name}: unknown kind {kind!r}")
        return ExportedWaveform(name, kind, meta["expression"], meta["result"], tables, sweeps)
    except (KeyError, TypeError) as exc:
        raise ValueError(f"{meta_path.name}: malformed ({exc!r})") from exc


def _json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"{path.name}: {exc}") from exc


def _read_csv(path: Path, columns: list[str], units: list[str], points: int, *, values=()) -> WaveformTable:
    try:
        with path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.reader(handle)
            header = next(reader, None)
            if header != list(columns):
                raise ValueError(f"{path.name}: header {header} is not {list(columns)}")
            rows = []
            for number, row in enumerate(reader, start=2):
                if len(row) != len(columns):
                    raise ValueError(f"{path.name}:{number}: {len(row)} field(s), not {len(columns)}")
                try:
                    rows.append(tuple(float(v) for v in row))
                except ValueError as exc:
                    raise ValueError(f"{path.name}:{number}: not a number ({exc})") from exc
    except OSError as exc:
        raise ValueError(f"{path.name}: {exc}") from exc
    if len(rows) != points:
        raise ValueError(f"{path.name}: {len(rows)} row(s), the meta file says {points}")
    return WaveformTable(path, list(columns), list(units), rows, list(values))


def _sibling(path: str, name: str) -> str:
    head, sep, _ = path.rpartition("/")
    return f"{head}{sep}{name}"


def _skill(value: str) -> str:
    if any(ord(c) < 32 or ord(c) == 127 for c in value):
        raise ValueError(f"control character in SKILL string {value!r}")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _check_selector(value: str, label: str) -> None:
    if not RESULT_SELECTOR_RE.match(value):
        raise ValueError(f"{label} is not a safe OCEAN result selector: {value!r}")
