"""OCEAN replay script generation and scalar-output parsing (Spectre/OCEAN kernel)."""

from __future__ import annotations

import csv
import math
import re
from dataclasses import dataclass, field
from pathlib import Path

from pydantic import BaseModel, Field, field_validator

from ic_opt.spec import Metric

RESULT_SELECTOR_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
WAVEFORM_RESULT_RE = re.compile(r'\?result\s+"([^"]+)"')
UNSAFE_RE = re.compile(r"outfile\(|system\(|\{\{")
SAFE_IDENTIFIER_RE = re.compile(r"[^A-Za-z0-9_]")
SCALARS_HEADER = ["metric", "value", "unit", "status", "message"]
OPPOINTS_HEADER = "instance\tquantity\tvalue"
# D8: the quantities kept per transistor, fixed. `gm` first: an instance without it is not a transistor and is left out.
OP_QUANTITIES = ("gm", "region", "ids", "vgs", "vds", "vbs", "vth", "vdsat", "gds", "gmoverid", "cgs", "cgd")


class WaveformExport(BaseModel):
    name: str = Field(pattern=r"^[A-Za-z_][A-Za-z0-9_]*$")
    expression: str = Field(min_length=1)
    testbench: str | None = None

    @field_validator("expression")
    @classmethod
    def _safe(cls, value: str) -> str:
        if UNSAFE_RE.search(value):
            raise ValueError("waveform expression must not contain outfile(, system( or {{")
        return value


@dataclass
class ScalarRow:
    value: float | None
    unit: str
    status: str            # "pass" | "fail"
    message: str = ""


@dataclass
class Scalars:
    rows: dict[str, ScalarRow] = field(default_factory=dict)
    waveforms: dict[str, Path | None] = field(default_factory=dict)   # export name -> local csv path (None: returned nil)
    attempts: int = 1
    oppoints: Path | None = None           # local oppoints.tsv (None: not asked for)


def replay_script(metrics: list[Metric], waveforms: list[WaveformExport], *, psf_dir: str, scalars_file: str,
                  waveform_dir: str, oppoint_result: str | None = None, oppoints_file: str | None = None) -> str:
    """SKILL that reads ``psf_dir`` and writes one TSV row per metric plus waveform CSVs and, with ``oppoint_result``
    (the netlist's ``info what=oppoint where=rawfile`` statement), the operating points to ``oppoints_file``.

    All paths are relative to the OCEAN working directory.
    """
    lines = [
        "; Generated by ic-opt: metric expressions copied verbatim from spec.yaml",
        f"openResults({_skill(psf_dir)})",
        f"out = outfile({_skill(scalars_file)})",
        'fprintf(out "' + "\\t".join(SCALARS_HEADER) + '\\n")',
    ]
    for metric in metrics:
        if metric.result is not None:
            _check_selector(metric.result, f"metric {metric.name} result")
            lines.append(f"selectResult('{metric.result})")
        lines += [
            f"; metric: {metric.name}",
            f"icoptResult = errset({metric.expression} t)",
            "if(icoptResult then",
            "  icoptValue = car(icoptResult)",
            "  if(numberp(icoptValue) then",
            f'    fprintf(out "%s\\t%.16g\\t%s\\tpass\\t\\n" {_skill(metric.name)} icoptValue {_skill(metric.unit)})',
            "  else",
            "    if(null(icoptValue) then",             # SKILL's type(nil) is `list`: say what it is
            f'      fprintf(out "%s\\t\\t%s\\tfail\\tno_value:nil\\n" {_skill(metric.name)} {_skill(metric.unit)})',
            "    else",
            f'      fprintf(out "%s\\t\\t%s\\tfail\\tnon_scalar:%L\\n" {_skill(metric.name)} {_skill(metric.unit)} type(icoptValue))',
            "    )",
            "  )",
            "else",
            f'  fprintf(out "%s\\t\\t%s\\tfail\\texpression_error\\n" {_skill(metric.name)} {_skill(metric.unit)})',
            ")",
        ]
    for wf in waveforms:
        var = SAFE_IDENTIFIER_RE.sub("_", wf.name)
        lines.append(f"; waveform export: {wf.name}")
        selector = WAVEFORM_RESULT_RE.search(wf.expression)
        if selector:
            _check_selector(selector.group(1), f"waveform {wf.name} result")
            lines.append(f"selectResult('{selector.group(1)})")
        csv_path = f"{waveform_dir}/{wf.name}.csv"
        lines += [
            f"icoptWave_{var} = {wf.expression}",
            f"if(icoptWave_{var} then",
            f'  icoptWaveOut_{var} = outfile({_skill(csv_path)} "w")',
            f"  ocnPrint(?output icoptWaveOut_{var} ?separator \",\" ?numberNotation 'scientific icoptWave_{var})",
            f"  close(icoptWaveOut_{var})",
            "else",
            f"  ; waveform export {wf.name} returned nil",
            ")",
        ]
    lines.append("close(out)")
    if oppoint_result is not None:
        lines += oppoint_script(oppoint_result, oppoints_file)
    lines.append("exit()")
    return "\n".join(lines) + "\n"


def oppoint_script(result: str, oppoints_file: str) -> list[str]:
    """The replay script's operating-point part. It runs after the metrics and waveforms, with their file closed, so it
    cannot change one. Every call that can fail is inside ``errset``; rows are collected first and written only when the
    whole read went through, so a failure leaves the file empty (as does a result without operating points).

    OCEAN names a result after the statement only when the statement has one of the design environment's own names
    (``dcOpInfo``, a symbol); any other statement's result is the string ``<name>-info`` (``"icoptOpInfo-info"``), and
    selecting the bare name fails with "Results ... are not available" (real run, 2026-09-28). So the result is looked up
    in ``results()`` under both forms. A quantity is read with ``pv`` from that result -- the call that returned numbers
    in that run for both forms --, then with ``OP``, which reads the design environment's own result only, under the name
    as ``outputs()`` gives it and with a leading ``/``.
    Instance names are written as ``outputs()`` gives them, with ``\\``, tab and newline escaped
    (:func:`parse_oppoints` undoes it)."""
    _check_selector(result, "operating-point result")
    quantities = " ".join(_skill(q) for q in OP_QUANTITIES[1:])
    return [
        "; operating points (ic-opt): after the metrics, whose file is closed; nothing here can change one",
        "procedure(icoptOpEscape(s)",
        "  let((escaped c)",
        '    escaped = ""',
        "    for(i 1 strlen(s)",
        "      c = substring(s i 1)",
        r'      escaped = strcat(escaped cond((equal(c "\\") "\\\\") (equal(c "\t") "\\t") (equal(c "\n") "\\n") (t c)))',
        "    )",
        "    escaped",
        "  )",
        ")",
        "icoptOpResult = nil",
        "foreach(icoptOpCandidate car(errset(results()))",
        "  let((name)",
        '    name = sprintf(nil "%s" icoptOpCandidate)',
        f"    when(!icoptOpResult && (equal(name {_skill(result)}) || equal(name {_skill(result + '-info')}))",
        "      icoptOpResult = icoptOpCandidate",
        "    )",
        "  )",
        ")",
        "procedure(icoptOpValue(inst q)",
        "  let((v)",
        "    v = car(errset(pv(inst q ?result icoptOpResult)))",
        "    unless(numberp(v) v = car(errset(OP(inst q))))",
        '    unless(numberp(v) || equal(substring(inst 1 1) "/") v = car(errset(OP(strcat("/" inst) q))))',
        "    if(numberp(v) v nil)",
        "  )",
        ")",
        "icoptOpRows = nil",
        "icoptOpRead = errset(",
        "  when(icoptOpResult && errset(selectResult(icoptOpResult))",
        "    foreach(icoptOpInst car(errset(outputs()))",
        "      errset(",
        "        let((name gm row v)",
        "          name = if(symbolp(icoptOpInst) get_pname(icoptOpInst) icoptOpInst)",
        f"          gm = icoptOpValue(name {_skill(OP_QUANTITIES[0])})",
        "          when(gm",
        rf'            row = list(sprintf(nil "%s\t{OP_QUANTITIES[0]}\t%.16g\n" icoptOpEscape(name) float(gm)))',
        f"            foreach(q list({quantities})",
        "              v = icoptOpValue(name q)",
        r'              when(v row = cons(sprintf(nil "%s\t%s\t%.16g\n" icoptOpEscape(name) q float(v)) row))',
        "            )",
        "            icoptOpRows = append(icoptOpRows reverse(row))",
        "          )",
        "        )",
        "      )",
        "    )",
        "  )",
        ")",
        f'icoptOpOut = car(errset(outfile({_skill(oppoints_file)} "w")))',
        "when(icoptOpOut",
        "  when(icoptOpRead && icoptOpRows",
        r'    fprintf(icoptOpOut "instance\tquantity\tvalue\n")',          # OPPOINTS_HEADER
        '    foreach(icoptOpRow icoptOpRows fprintf(icoptOpOut "%s" icoptOpRow))',
        "  )",
        "  close(icoptOpOut)",
        ")",
    ]


def parse_oppoints(path: Path) -> dict[str, dict[str, float]] | None:
    """``oppoints.tsv`` -> {instance: {quantity: value}}; None when the file is missing or holds no row (no operating
    points in the results). Instances without ``gm`` and non-finite values are left out, as the script leaves out what
    has no number. A malformed row is an error (ValueError): the extract stage then keeps no operating points."""
    if not path.exists():
        return None
    text = path.read_bytes().decode("utf-8")           # not read_text: a carriage return inside a name stays in it
    rows = [line for line in text.split("\n") if line]
    if not rows:
        return None
    if rows[0] != OPPOINTS_HEADER:
        raise ValueError(f"unexpected operating-point header {rows[0]!r}")
    table: dict[str, dict[str, float]] = {}
    for line in rows[1:]:
        fields = line.split("\t")
        if len(fields) != 3 or fields[1] not in OP_QUANTITIES:
            raise ValueError(f"malformed operating-point row {line!r}")
        value = float(fields[2])
        if math.isfinite(value):
            table.setdefault(_unescape(fields[0]), {})[fields[1]] = value
    table = {name: q for name, q in table.items() if "gm" in q}
    return table or None


def _unescape(name: str) -> str:
    return re.sub(r"\\(.)", lambda m: {"t": "\t", "n": "\n"}.get(m.group(1), m.group(1)), name)


def parse_scalars(path: Path) -> dict[str, ScalarRow]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if reader.fieldnames != SCALARS_HEADER:
            raise ValueError(f"unexpected scalar header {reader.fieldnames}")
        rows: dict[str, ScalarRow] = {}
        for row in reader:
            name = row["metric"]
            value: float | None = None
            if row["status"] == "pass":
                try:
                    value = float(row["value"])
                except ValueError as exc:
                    raise ValueError(f"metric {name} value is not numeric: {row['value']!r}") from exc
                if not math.isfinite(value):
                    value = None
                    row["status"], row["message"] = "fail", "non_finite"
            rows[name] = ScalarRow(value, row["unit"], row["status"], row["message"])
    return rows


def _skill(value: str) -> str:
    if any(ord(c) < 32 or ord(c) == 127 for c in value):
        raise ValueError(f"control character in SKILL string {value!r}")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _check_selector(value: str, label: str) -> None:
    if not RESULT_SELECTOR_RE.match(value):
        raise ValueError(f"{label} is not a safe OCEAN result selector: {value!r}")
